name: Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  vale:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run Vale
        uses: errata-ai/vale-action@d89dee975228ae261d22c15adcd03578634d429c # v2
        with:
          files: content
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
